select a.experiment_id, 
a.variant_id,
a.start_date,
a.end_date,
bucketing_id,
a.visits,
cvr,
mean_prolist_rev,
mean_cvr_prolist_rev,
mean_ltv_rev,
mean_osa_rev,
mean_comm_rev,
mean_total_rev,
mean_total_rev_ex_ncp,
mean_total_rev_cb,
mean_total_rev_ex_ncp_cb,
mean_aov_cb,
std_prolist_rev,
std_cvr_prolist_rev,
std_ltv_rev,
std_osa_rev,
std_comm_rev,
std_total_rev,
std_total_rev_ex_ncp,
std_total_rev_cb,
std_total_rev_ex_ncp_cb,
std_aov_cb,
safe_divide(a.visits, b.visits) - 1 as visits_diff,
safe_divide(a.cvr, b.conversion_rate) - 1 as cvr_diff,
safe_divide(a.mean_prolist_rev, b.prolist_total_spend_per_browser/100) - 1 as prolist_total_spend_per_browser_diff,
safe_divide(a.mean_osa_rev*bucketing_id, b.offsite_ads_revenue_sum/100) - 1 as offsite_ads_revenue_sum_diff,
from etsy-data-warehouse-dev.tnormil.lex_dev_catapult_stat_0224 a
left join `etsy-data-warehouse-dev.tnormil.lex_prod_catapult_stat` b using (experiment_id, variant_id)
